# Generated by Django 4.1.6 on 2023-02-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0002_alter_super_super_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='super_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
        ),
    ]
